#!/bin/sh

# bring up containerd
printf "\nStarting containerd\n"
/usr/bin/containerd &

# wait for socket to be there
while [ ! -S /run/containerd/containerd.sock ]
do
	sleep 0.1
done

# start service containers

if [ -d /containers/services ]
then
	for f in $(find /containers/services -mindepth 1 -maxdepth 1 | sort)
	do
		/bin/mount --bind "$f/rootfs" "$f/rootfs"
		mount -o remount,rw "$f/rootfs"
		service start "$(basename $f)"
	done
fi
