#!/bin/sh

# start service containers

if [ -d /containers/services ]
then
	for f in $(find /containers/services -mindepth 1 -maxdepth 1 | sort)
	do
		/bin/mount --bind "$f/rootfs" "$f/rootfs"
		mount -o remount,rw "$f/rootfs"
	done
fi

service system-init
