#!/bin/sh

# start onshutdown containers, run to completion

if [ -d /containers/onshutdown ]
then
	for f in $(find /containers/onshutdown -mindepth 1 -maxdepth 1 | sort)
	do
		base="$(basename $f)"
		/bin/mount --bind "$f/rootfs" "$f/rootfs"
		mount -o remount,rw "$f/rootfs"
		/usr/bin/runc run --bundle "$f" "$(basename $f)"
		printf " - $base\n"
	done
fi
