# Tag: 97cc67f5569c437175f2e54b3c3b9a96a8615a16
FROM mobylinux/alpine-qemu@sha256:80e17a465b332d774fd91b53c0bcb18ed0ea8a77c17bf8d8451c57a8ab8b4e66

COPY alpine/gce.img.tar.gz .
RUN zcat gce.img.tar.gz | tar xf -

ENTRYPOINT [ "qemu-system-x86_64", "-serial", "stdio", "-drive", "file=disk.raw,format=raw", "-m", "2048", "-vnc", "none" ]
