# Tag: 0e76bc8d0bd0f0cd505d0353b3a550266c52133c
FROM mobylinux/toybox-media@sha256:69f9ae2e9192746f4f588d15ed15b9d8e005bbca394cfff1cfbbef023c4a7eed

ADD \
  alpine/initrd.img \
  alpine/kernel/x86_64/vmlinuz64 \
  alpine/kernel/x86_64/vmlinux \
  alpine/kernel/x86_64/kernel-headers.tar \
  alpine/kernel/x86_64/kernel-dev.tar \
  alpine/mobylinux-efi.iso \
  alpine/mobylinux.efi \
  / 
