FROM mobylinux/alpine-qemu:1f3de121e9dea39a198413344a72049839bea91b

COPY alpine/mobylinux-bios.iso .

ENTRYPOINT [ "qemu-system-x86_64", "-serial", "stdio", "-cdrom", "./mobylinux-bios.iso", "-m", "2048", "-vnc", "none" ]
