FROM justincormack/alpine-qemu

COPY alpine/initrd.img.gz .
COPY alpine/kernel/vmlinuz64 .

ENTRYPOINT [ "qemu-system-x86_64", "-serial", "stdio", "-kernel", "vmlinuz64", "-initrd", "initrd.img.gz", "-m", "2048", "-append", "earlyprintk=serial console=ttyS0 noapic", "-vnc", "none" ]
