FROM mobylinux/toybox-media:e22a41942621b5655bd952b7715d695eaed32647

ADD \
  alpine/initrd.img \
  alpine/kernel/x86_64/vmlinuz64 \
  alpine/kernel/x86_64/vmlinux \
  alpine/mobylinux-efi.iso \
  alpine/mobylinux.efi \
  / 
