FROM ubuntu:15.10

COPY alpine/initrd-arm.img .
COPY alpine/kernel/zImage .
COPY alpine/kernel/dtb .

RUN apt-get update && apt-get install -y qemu-system-arm

RUN gzip -9 initrd-arm.img

ENTRYPOINT [ "qemu-system-arm", "-machine", "vexpress-a15", "-cpu", "cortex-a15", "-no-reboot", "-serial", "stdio", "-kernel", "zImage", "-initrd", "initrd-arm.img.gz", "-dtb", "dtb", "-m", "256", "-append", "console=ttyAMA0,38400n8", "-vnc", "none" ]
