FROM mobylinux/alpine-qemu:a4558b652e94f54848f16d0fd5d2a9ebfd090070

COPY alpine/mobylinux-bios.iso .

ENTRYPOINT [ "qemu-system-x86_64", "-serial", "stdio", "-cdrom", "./mobylinux-bios.iso", "-m", "2048", "-vnc", "none" ]
