FROM debian:jessie

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
        rsyslog \
        openssl \
        ca-certificates \
        ssh \
        git \
        parted \
        sudo \
        net-tools \
        ifupdown \
        python \
        python-pyasn1 \
        python-setuptools \
        python-rpm

RUN git clone https://github.com/Azure/WALinuxAgent /WALinuxAgent
WORKDIR /WALinuxAgent
RUN python setup.py install
COPY ./waagent.conf /etc/waagent.conf
RUN cp /WALinuxAgent/bin/* /usr/sbin/

RUN chmod +x /usr/sbin/waagent && \
    ln -sf /dev/stdout /var/log/waagent.log

ENTRYPOINT ["/usr/sbin/waagent"]
