#!/bin/sh

# start memlogd container

/usr/bin/startmemlogd

# start onboot containers, run to completion

if [ -d /containers/onboot ]
then
	for f in $(find /containers/onboot -mindepth 1 -maxdepth 1 | sort)
	do
		base="$(basename $f)"
		/bin/mount --bind "$f/rootfs" "$f/rootfs"
		mount -o remount,rw "$f/rootfs"
		/usr/bin/logwrite -n "$(basename $f)" /usr/bin/runc run --bundle "$f" "$(basename $f)"
		printf " - $base\n"
	done
fi

# start service containers

if [ -d /containers/services ]
then
	for f in $(find /containers/services -mindepth 1 -maxdepth 1 | sort)
	do
		base="$(basename $f)"
		/bin/mount --bind "$f/rootfs" "$f/rootfs"
		mount -o remount,rw "$f/rootfs"
		log="/var/log/$base.log"
		/usr/bin/logwrite -n "$(basename $f)" ctr run --runtime-config "$f/config.json" --rootfs "$f/rootfs" --id "$(basename $f)" </dev/null 2>$log >$log &
		printf " - $base\n"
	done
fi

wait
