FROM ocaml/opam:alpine-3.5_ocaml-4.04.0
RUN cd /home/opam/opam-repository && git pull && opam update -u

## pins for priv

# to bring eth0 up
RUN opam pin add tuntap 1.0.0 -n
RUN opam pin add mirage-net-fd 0.2.0 -n

## pins for calf

RUN opam pin add charrua-client https://github.com/yomimono/charrua-client.git#state-halfway -n

## depdendencies

RUN opam depext -iy \
    irmin-unix cohttp decompress rawlink tuntap jbuilder irmin-watcher inotify \
    rresult lwt capnp charrua-client mirage-net-fd ptime bos                   \
    mirage-flow-lwt mirage-channel-lwt mirage-types-lwt

RUN sudo mkdir -p /src /bin
COPY . /src
COPY init-dev.sh /home/opam/init-dev.sh

USER opam
WORKDIR /src

ENTRYPOINT ["/bin/sh", "/home/opam/init-dev.sh"]
