ARG source=nosuchimage
FROM ${source}

ARG ARCH
ARG KERNEL_SERIES
ARG DEBUG

RUN mkdir /config
COPY kernel_config.* /config/
COPY makeconfig.sh /config

RUN /config/makeconfig.sh ${ARCH} ${KERNEL_SERIES}
