CONFIG_CRYPTO_CMAC=y
CONFIG_CRYPTO_DEV_VIRTIO=m
CONFIG_HYPERV_SOCK=y
CONFIG_LWTUNNEL_BPF=y
# CONFIG_NET_VENDOR_SYNOPSYS is not set
# CONFIG_SYNC_FILE is not set
# CONFIG_TIMER_STATS is not set
CONFIG_UPROBE_EVENT=y
