CONFIG_HYPERV_VSOCKETS=y
CONFIG_INPUT_MOUSEDEV=y
CONFIG_INPUT_MOUSEDEV_SCREEN_X=1024
CONFIG_INPUT_MOUSEDEV_SCREEN_Y=768
CONFIG_PTP_1588_CLOCK_KVM=y
# CONFIG_R8169 is not set
# CONFIG_RCU_TRACE is not set
