FROM alpine:3.5
RUN \
  apk update && apk upgrade && \
  apk add \
  build-base \
  argp-standalone \
  automake \
  bash \
  bc \
  binutils-dev \
  curl \
  git \
  gmp-dev \
  installkernel \
  kmod \
  libelf-dev \
  linux-headers \
  ncurses-dev \
  sed \
  squashfs-tools \
  tar \
  xz \
  && true
