FROM aarch64/alpine:3.5
RUN apk --no-cache add --update --upgrade --purge   \
        argp-standalone                             \
        automake                                    \
        bash                                        \
        bc                                          \
        binutils-dev                                \
        build-base                                  \
        curl                                        \
        git                                         \
        gmp-dev                                     \
        installkernel                               \
        kmod                                        \
        libelf-dev                                  \
        linux-headers                               \
        ncurses-dev                                 \
        sed                                         \
        squashfs-tools                              \
        tar                                         \
        xz
