# autogenerated by mkversions
COMMON_IMAGES := \
  kube-proxy-amd64\:v1.8.0@sha256\:3da0e03a49404119fbf104037b7ac24d871842bf565a4364390a7d6ea60f48a0 \
  k8s-dns-sidecar-amd64\:1.14.5@sha256\:9aab42bf6a2a068b797fe7d91a5d8d915b10dbbc3d6f2b10492848debfba6044 \
  k8s-dns-kube-dns-amd64\:1.14.5@sha256\:1a3fc069de481ae690188f6f1ba4664b5cc7760af37120f70c86505c79eea61d \
  k8s-dns-dnsmasq-nanny-amd64\:1.14.5@sha256\:46b933bb70270c8a02fa6b6f87d440f6f1fce1a5a2a719e164f83f7b109f7544 \
  pause-amd64\:3.0@sha256\:163ac025575b775d1c0f9bf0bdd0f086883171eb475b5068e7defa4ca9e76516

CONTROL_PLANE_IMAGES := \
  kube-apiserver-amd64\:v1.8.0@sha256\:e7377096f0b88b0fcc5dce1c56aed002f999f095a30676c68b8f686a6bb1e943 \
  kube-controller-manager-amd64\:v1.8.0@sha256\:9b1ae1007d3d0f4272e7ad5e8a6d34a1f49c2e3a33339773864aed525a667d26 \
  kube-scheduler-amd64\:v1.8.0@sha256\:79b5b697b1bc1023b5f18a792ea7020c4ad8403d861169b1b420d3fe673b9fe4 \
  etcd-amd64\:3.0.17@sha256\:d83d3545e06fb035db8512e33bd44afb55dea007a3abd7b17742d3ac6d235940
