# autogenerated by mkversions
COMMON_IMAGES := \
  kube-proxy-amd64\:v1.8.2@sha256\:8b81f3be506ca13df59731a75cc7795aeeff64cad48202067b431b9c2a4d91a9 \
  k8s-dns-sidecar-amd64\:1.14.5@sha256\:9aab42bf6a2a068b797fe7d91a5d8d915b10dbbc3d6f2b10492848debfba6044 \
  k8s-dns-kube-dns-amd64\:1.14.5@sha256\:1a3fc069de481ae690188f6f1ba4664b5cc7760af37120f70c86505c79eea61d \
  k8s-dns-dnsmasq-nanny-amd64\:1.14.5@sha256\:46b933bb70270c8a02fa6b6f87d440f6f1fce1a5a2a719e164f83f7b109f7544 \
  pause-amd64\:3.0@sha256\:163ac025575b775d1c0f9bf0bdd0f086883171eb475b5068e7defa4ca9e76516

CONTROL_PLANE_IMAGES := \
  kube-apiserver-amd64\:v1.8.2@sha256\:3e980f4b57292568ea8c87be462cf0583e40bbc2dbfff71d0d9e19beda3cb74b \
  kube-controller-manager-amd64\:v1.8.2@sha256\:c2cd4acd4238b2f2526abf5ba546d4e6f4a46618ad5747a539e8a72c294a7482 \
  kube-scheduler-amd64\:v1.8.2@sha256\:7c920b718509e8cf811c69178526d84ebfab2bdbb95949f6e82eb5233e7b5f0e \
  etcd-amd64\:3.0.17@sha256\:d83d3545e06fb035db8512e33bd44afb55dea007a3abd7b17742d3ac6d235940
