FROM alpine:3.4
RUN \
  apk update && apk upgrade && \
  apk add \
  alpine-sdk \
  argp-standalone \
  automake \
  bash \
  bc \
  cmake \
  curl \
  gmp-dev \
  installkernel \
  kmod \
  linux-headers \
  ncurses-dev \
  perl \
  sed \
  squashfs-tools \
  syslinux \
  unzip \
  util-linux-dev \
  vim \
  xz \
  && true
