#!/bin/sh

if [ -f /etc/issue ]; then
	for opt in $(cat /proc/cmdline); do
		case "$opt" in
		console=*)
			fulltty=${opt#console=}
			tty=${fulltty%,*}
			if [ -c "/dev/$tty" ] ; then
				cat /etc/issue >> "/dev/$tty"
			fi
		esac
	done
fi
