FROM docker4x/azure-vhd-utils@sha256:2fd21df46e65d2f4007133e664a0a81611d8d23f7badedce56ca8d2f9ca39f94

RUN mkdir /build
RUN mkdir /scripts
WORKDIR /scripts
COPY ./kernel/x86_64/vmlinuz64 /build
COPY ./initrd.img /build
COPY ./cloud/azure/syslinux.cfg /build/syslinux.cfg
COPY ./cloud/build-common.sh .
COPY ./cloud/azure/bake-azure.sh .
COPY ./cloud/azure/azure.sh .

VOLUME ["/tmp"]
ENTRYPOINT ["./azure.sh"]
