FROM alpine

RUN apk add --update \
    python \
    py-pip \
    curl \
    e2fsprogs \
    jq \
    syslinux
RUN pip install -U awscli
RUN mkdir -p /scripts
WORKDIR /scripts
COPY ./build-common.sh .
COPY ./aws/common.sh .
COPY ./aws/bake-ami.sh .

ENTRYPOINT ["./bake-ami.sh"]
