FROM mobylinux/alpine-aws:9f937d52372fc1a8a75b57a305d81ca88c522f78

RUN mkdir /build
RUN mkdir /scripts
WORKDIR /scripts
COPY ./kernel/x86_64/vmlinuz64 /build
COPY ./initrd.img /build
COPY ./cloud/aws/syslinux.cfg /build/syslinux.cfg
COPY ./cloud/build-common.sh .
COPY ./cloud/aws/common.sh .
COPY ./cloud/aws/aws.sh .
COPY ./cloud/aws/bake-ami.sh .

ENTRYPOINT ["./aws.sh"]
