# Tag: da39a3ee5e6b4b0d3255bfef95601890afd80709
FROM mobylinux/alpine-aws@sha256:70799a47473700b5000557f07c0c2b6d293b017a5388c21dd5abe94f6b878632

RUN mkdir /build
RUN mkdir /scripts
WORKDIR /scripts
COPY ./kernel/x86_64/vmlinuz64 /build
COPY ./initrd.img /build
COPY ./cloud/aws/syslinux.cfg /build/syslinux.cfg
COPY ./cloud/build-common.sh .
COPY ./cloud/aws/common.sh .
COPY ./cloud/aws/aws.sh .
COPY ./cloud/aws/bake-ami.sh .

ENTRYPOINT ["./aws.sh"]
