FROM mobylinux/go-compile:3afebc59c5cde31024493c3f91e6102d584a30b9@sha256:e0786141ea7df8ba5735b63f2a24b4ade9eae5a02b0e04c4fca33b425ec69b0a

ENV GOPATH=/go
ENV PATH=/go/bin:/usr/local/go/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

# The project sources
VOLUME ["/go/src/github.com/docker/infrakit.hyperkit"]
WORKDIR /go/src/github.com/docker/infrakit.hyperkit

ENTRYPOINT ["make"]
