ARG BUILD_IMAGE
ARG KERNEL_VERSION
ARG PKG_HASH

FROM linuxkit/kernel:${KERNEL_VERSION}-${PKG_HASH} AS ksrc

FROM ${BUILD_IMAGE} AS build

ARG ZFS_VERSION=2.2.9

# Kernel headers
COPY --from=ksrc /kernel-dev.tar /
RUN tar xf kernel-dev.tar

# Also extract the kernel modules
COPY --from=ksrc /kernel.tar /
RUN tar xf kernel.tar

# Also extract the kernel source
COPY --from=ksrc /linux.tar.xz /linux.tar.xz
RUN tar xf linux.tar.xz -C /usr/src

# Fix kernel source tree and add config
RUN cp -r /usr/src/linux-headers-*/.config /usr/src/linux
RUN cp -r /usr/src/linux-headers-*/* /usr/src/linux

RUN apk add \
    attr-dev \
    autoconf \
    automake \
    bash \
    bison \
    build-base \
    elfutils-dev \
    file \
    flex \
    git \
    gmp-dev \
    installkernel \
    kmod \
    libtirpc-dev \
    libtool \
    mpc1-dev \
    mpfr-dev \
    openssl-dev \
    util-linux-dev \
    zlib-dev

RUN git config --global url.https://.insteadOf git://

ENV ZFS_REPO=https://github.com/zfsonlinux/zfs.git
ENV ZFS_COMMIT=zfs-${ZFS_VERSION}
RUN git clone ${ZFS_REPO} && \
    cd zfs && \
    git checkout ${ZFS_COMMIT}

RUN ( cd zfs && \
    ./autogen.sh && \
    ./configure --with-linux=/usr/src/linux && \
    ./scripts/make_gitrev.sh && \
    cd module && \
    make -j "$(getconf _NPROCESSORS_ONLN)" && \
    make install )

# Run depmod against the new module directory.
RUN cd /lib/modules && \
    depmod -ae *

FROM scratch
ENTRYPOINT []
CMD []
WORKDIR /
COPY --from=build /lib/modules/ /lib/modules/
